// <auto-generated />
using System;
using GumrukApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GumrukApi.Migrations
{
    [DbContext(typeof(GumrukDbContext))]
    [Migration("20260815171453_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GumrukApi.Models.AnalizKaydi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("BenzerlikSkoru")
                        .HasColumnType("double precision");

                    b.Property<string>("BeyanEdilenGtip")
                        .HasColumnType("text");

                    b.Property<string>("EsyaTanimi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OnerilenGtip")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RiskSeviyesi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AnalizKayitlari");
                });

            modelBuilder.Entity("GumrukApi.Models.Feedback", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AnalizKaydiId")
                        .HasColumnType("integer");

                    b.Property<bool>("DogruMu")
                        .HasColumnType("boolean");

                    b.Property<string>("Notlar")
                        .HasColumnType("text");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AnalizKaydiId");

                    b.ToTable("Feedbackler");
                });

            modelBuilder.Entity("GumrukApi.Models.KuralKutuphanesi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("IlgiliPozisyonlar")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("KuralId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("KuralMetni")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("KuralKutuphaneleri");
                });

            modelBuilder.Entity("GumrukApi.Models.Feedback", b =>
                {
                    b.HasOne("GumrukApi.Models.AnalizKaydi", "AnalizKaydi")
                        .WithMany()
                        .HasForeignKey("AnalizKaydiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnalizKaydi");
                });
#pragma warning restore 612, 618
        }
    }
}
